// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateMessageRequest struct {
	Rid       uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	SessionId int64  `protobuf:"varint,11,opt,name=sessionId" json:"sessionId,omitempty"`
	Type      int32  `protobuf:"varint,12,opt,name=type" json:"type,omitempty"`
	Content   string `protobuf:"bytes,13,opt,name=Content,json=content" json:"Content,omitempty"`
	Id        string `protobuf:"bytes,14,opt,name=Id,json=id" json:"Id,omitempty"`
}

func (m *CreateMessageRequest) Reset()                    { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()               {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *CreateMessageRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateMessageRequest) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CreateMessageRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreateMessageRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateMessageReply struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *CreateMessageReply) Reset()                    { *m = CreateMessageReply{} }
func (m *CreateMessageReply) String() string            { return proto.CompactTextString(m) }
func (*CreateMessageReply) ProtoMessage()               {}
func (*CreateMessageReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *CreateMessageReply) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateMessageReply) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateMessageReply) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMessageRequest)(nil), "pb.CreateMessageRequest")
	proto.RegisterType((*CreateMessageReply)(nil), "pb.CreateMessageReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Message service

type MessageClient interface {
	// Sends a greeting
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageReply, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageReply, error) {
	out := new(CreateMessageReply)
	err := grpc.Invoke(ctx, "/pb.Message/CreateMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Message service

type MessageServer interface {
	// Sends a greeting
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageReply, error)
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Message/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessage",
			Handler:    _Message_CreateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xb1, 0x4a, 0xc5, 0x30,
	0x14, 0x86, 0x4d, 0x5a, 0x2d, 0xf7, 0x68, 0x2f, 0x72, 0x10, 0x39, 0x88, 0x43, 0xe8, 0x94, 0xa9,
	0x83, 0x3e, 0x42, 0xa7, 0x3b, 0x78, 0x87, 0xbc, 0x41, 0xdb, 0x1c, 0xa4, 0x50, 0x9b, 0xd8, 0xc4,
	0xa1, 0xbb, 0x0f, 0x2e, 0x4d, 0x05, 0xf1, 0xd2, 0xed, 0xcb, 0xf7, 0x93, 0x9f, 0x3f, 0x81, 0xf2,
	0x83, 0x43, 0x68, 0xdf, 0xb9, 0xf6, 0xb3, 0x8b, 0x0e, 0xa5, 0xef, 0xaa, 0x6f, 0x01, 0x0f, 0xcd,
	0xcc, 0x6d, 0xe4, 0xb7, 0x2d, 0x33, 0xfc, 0xf9, 0xc5, 0x21, 0xe2, 0x3d, 0x64, 0xf3, 0x60, 0x49,
	0x28, 0xa1, 0x73, 0xb3, 0x22, 0x3e, 0xc3, 0x21, 0x70, 0x08, 0x83, 0x9b, 0x4e, 0x96, 0x6e, 0x95,
	0xd0, 0x99, 0xf9, 0x13, 0x88, 0x90, 0xc7, 0xc5, 0x33, 0xdd, 0x29, 0xa1, 0xaf, 0x4d, 0x62, 0x24,
	0x28, 0x1a, 0x37, 0x45, 0x9e, 0x22, 0x95, 0x4a, 0xe8, 0x83, 0x29, 0xfa, 0xed, 0x88, 0x47, 0x90,
	0x27, 0x4b, 0xc7, 0x24, 0xe5, 0x60, 0xab, 0x33, 0xe0, 0xc5, 0x0a, 0x3f, 0x2e, 0x3b, 0x1b, 0x10,
	0xf2, 0xde, 0x59, 0x26, 0x99, 0x6e, 0x26, 0x5e, 0x9d, 0xe5, 0xd0, 0x53, 0xb6, 0xb9, 0x95, 0x5f,
	0xce, 0x50, 0xfc, 0x36, 0x61, 0x03, 0xe5, 0xbf, 0x6a, 0xa4, 0xda, 0x77, 0xf5, 0xde, 0x9b, 0x9f,
	0x1e, 0x77, 0x12, 0x3f, 0x2e, 0xd5, 0x55, 0x77, 0x93, 0x7e, 0xec, 0xf5, 0x27, 0x00, 0x00, 0xff,
	0xff, 0xc0, 0x09, 0xe1, 0x4e, 0x42, 0x01, 0x00, 0x00,
}
