// Code generated by protoc-gen-go.
// source: session.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SessionInfo struct {
	SessionId uint64 `protobuf:"varint,11,opt,name=sessionId" json:"sessionId,omitempty"`
}

func (m *SessionInfo) Reset()                    { *m = SessionInfo{} }
func (m *SessionInfo) String() string            { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()               {}
func (*SessionInfo) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *SessionInfo) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type CreateSessionRequest struct {
	Rid          uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	AppId        string `protobuf:"bytes,11,opt,name=appId" json:"appId,omitempty"`
	CreateUserId string `protobuf:"bytes,12,opt,name=createUserId" json:"createUserId,omitempty"`
	Count        int32  `protobuf:"varint,13,opt,name=count" json:"count,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *CreateSessionRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateSessionRequest) GetCreateUserId() string {
	if m != nil {
		return m.CreateUserId
	}
	return ""
}

func (m *CreateSessionRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateSessionReply struct {
	Rid        uint64         `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code       string         `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc       string         `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	SessionIds []*SessionInfo `protobuf:"bytes,11,rep,name=sessionIds" json:"sessionIds,omitempty"`
}

func (m *CreateSessionReply) Reset()                    { *m = CreateSessionReply{} }
func (m *CreateSessionReply) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionReply) ProtoMessage()               {}
func (*CreateSessionReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *CreateSessionReply) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionReply) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateSessionReply) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateSessionReply) GetSessionIds() []*SessionInfo {
	if m != nil {
		return m.SessionIds
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionInfo)(nil), "pb.SessionInfo")
	proto.RegisterType((*CreateSessionRequest)(nil), "pb.CreateSessionRequest")
	proto.RegisterType((*CreateSessionReply)(nil), "pb.CreateSessionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Session service

type SessionClient interface {
	// Sends a greeting
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error) {
	out := new(CreateSessionReply)
	err := grpc.Invoke(ctx, "/pb.Session/CreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Session service

type SessionServer interface {
	// Sends a greeting
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error)
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Session/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Session_CreateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}

func init() { proto.RegisterFile("session.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x36, 0x4d, 0xab, 0x74, 0xd2, 0xa0, 0x0c, 0x45, 0x06, 0xf1, 0x10, 0xf6, 0x14, 0x10, 0x22,
	0xd4, 0x47, 0xe8, 0x29, 0x17, 0x0f, 0x2b, 0x3e, 0x40, 0x93, 0x1d, 0xa1, 0x50, 0xb2, 0x6b, 0x76,
	0x0b, 0xf6, 0xe4, 0xab, 0xcb, 0xfe, 0xa0, 0xad, 0xe4, 0xf6, 0xcd, 0xf7, 0x33, 0xb3, 0x3b, 0x03,
	0xa5, 0x65, 0x6b, 0xf7, 0x7a, 0x68, 0xcc, 0xa8, 0x9d, 0xc6, 0x99, 0xe9, 0xc4, 0x13, 0x14, 0x6f,
	0x91, 0x6c, 0x87, 0x0f, 0x8d, 0x8f, 0xb0, 0x4c, 0x9e, 0x56, 0x51, 0x51, 0x65, 0xf5, 0x5c, 0xfe,
	0x11, 0xe2, 0x0b, 0xd6, 0xdb, 0x91, 0x77, 0x8e, 0x53, 0x44, 0xf2, 0xe7, 0x91, 0xad, 0xc3, 0x3b,
	0xc8, 0xc7, 0xbd, 0xa2, 0x2c, 0xf8, 0x3d, 0xc4, 0x35, 0x2c, 0x76, 0xc6, 0xa4, 0x1e, 0x4b, 0x19,
	0x0b, 0x14, 0xb0, 0xea, 0x43, 0xfe, 0xdd, 0xf2, 0xd8, 0x2a, 0x5a, 0x05, 0xf1, 0x82, 0xf3, 0xc9,
	0x5e, 0x1f, 0x07, 0x47, 0x65, 0x95, 0xd5, 0x0b, 0x19, 0x0b, 0xf1, 0x0d, 0xf8, 0x6f, 0xb2, 0x39,
	0x9c, 0x26, 0xe6, 0x22, 0xcc, 0x7b, 0xad, 0x98, 0x66, 0xa1, 0x73, 0xc0, 0x9e, 0x53, 0x6c, 0x7b,
	0xca, 0x23, 0xe7, 0x31, 0x3e, 0x03, 0xfc, 0x7e, 0xcb, 0x52, 0x51, 0xe5, 0x75, 0xb1, 0xb9, 0x6d,
	0x4c, 0xd7, 0x9c, 0x2d, 0x43, 0x9e, 0x59, 0x36, 0xaf, 0x70, 0x93, 0x24, 0xdc, 0x42, 0x79, 0xf1,
	0x16, 0x24, 0x1f, 0x9c, 0x5a, 0xcc, 0xc3, 0xfd, 0x84, 0x62, 0x0e, 0x27, 0x71, 0xd5, 0x5d, 0x87,
	0x13, 0xbc, 0xfc, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x49, 0xed, 0x49, 0x93, 0x01, 0x00, 0x00,
}
