// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package bean is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	WraperMessage
	DeviceRegisteRequest
	DeviceRegisteResponse
	DeviceLoginRequest
	DeviceLoginResponse
*/
package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// messageType = 1
type WraperMessage struct {
	Rid     uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *WraperMessage) Reset()                    { *m = WraperMessage{} }
func (m *WraperMessage) String() string            { return proto.CompactTextString(m) }
func (*WraperMessage) ProtoMessage()               {}
func (*WraperMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WraperMessage) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *WraperMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// messageType = 11
type DeviceRegisteRequest struct {
	Rid      uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	SsoToken string `protobuf:"bytes,11,opt,name=ssoToken" json:"ssoToken,omitempty"`
	AppId    string `protobuf:"bytes,12,opt,name=appId" json:"appId,omitempty"`
	DeviceId string `protobuf:"bytes,13,opt,name=deviceId" json:"deviceId,omitempty"`
	Platform string `protobuf:"bytes,14,opt,name=platform" json:"platform,omitempty"`
}

func (m *DeviceRegisteRequest) Reset()                    { *m = DeviceRegisteRequest{} }
func (m *DeviceRegisteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceRegisteRequest) ProtoMessage()               {}
func (*DeviceRegisteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceRegisteRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceRegisteRequest) GetSsoToken() string {
	if m != nil {
		return m.SsoToken
	}
	return ""
}

func (m *DeviceRegisteRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeviceRegisteRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceRegisteRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

// messageType = 12
type DeviceRegisteResponse struct {
	Rid   uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc  string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Token string `protobuf:"bytes,11,opt,name=token" json:"token,omitempty"`
}

func (m *DeviceRegisteResponse) Reset()                    { *m = DeviceRegisteResponse{} }
func (m *DeviceRegisteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceRegisteResponse) ProtoMessage()               {}
func (*DeviceRegisteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeviceRegisteResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceRegisteResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DeviceRegisteResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *DeviceRegisteResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// messageType = 13
type DeviceLoginRequest struct {
	Rid      uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Token    string `protobuf:"bytes,11,opt,name=token" json:"token,omitempty"`
	AppId    string `protobuf:"bytes,12,opt,name=appId" json:"appId,omitempty"`
	DeviceId string `protobuf:"bytes,13,opt,name=deviceId" json:"deviceId,omitempty"`
	Platform string `protobuf:"bytes,14,opt,name=platform" json:"platform,omitempty"`
}

func (m *DeviceLoginRequest) Reset()                    { *m = DeviceLoginRequest{} }
func (m *DeviceLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceLoginRequest) ProtoMessage()               {}
func (*DeviceLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeviceLoginRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeviceLoginRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeviceLoginRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceLoginRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

// messageType = 14
type DeviceLoginResponse struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *DeviceLoginResponse) Reset()                    { *m = DeviceLoginResponse{} }
func (m *DeviceLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceLoginResponse) ProtoMessage()               {}
func (*DeviceLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeviceLoginResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceLoginResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DeviceLoginResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*WraperMessage)(nil), "bean.WraperMessage")
	proto.RegisterType((*DeviceRegisteRequest)(nil), "bean.DeviceRegisteRequest")
	proto.RegisterType((*DeviceRegisteResponse)(nil), "bean.DeviceRegisteResponse")
	proto.RegisterType((*DeviceLoginRequest)(nil), "bean.DeviceLoginRequest")
	proto.RegisterType((*DeviceLoginResponse)(nil), "bean.DeviceLoginResponse")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x89, 0x5b, 0xff, 0xec, 0xec, 0xae, 0x48, 0x5c, 0x21, 0x78, 0x2a, 0x3d, 0xf5, 0xe4,
	0xc5, 0xa3, 0x57, 0x2f, 0x0b, 0x8a, 0x10, 0x04, 0xcf, 0xd9, 0x66, 0x2c, 0xc5, 0x6d, 0x13, 0x33,
	0xd1, 0x0f, 0xe1, 0xd1, 0x4f, 0x2c, 0xc9, 0x50, 0x51, 0xa9, 0x27, 0xbd, 0xcd, 0x6f, 0x1e, 0x6f,
	0xfa, 0x5e, 0x09, 0x2c, 0x76, 0xae, 0xed, 0x86, 0x0b, 0x1f, 0x5c, 0x74, 0xb2, 0xd8, 0xa2, 0x19,
	0xaa, 0x2b, 0x58, 0x3d, 0x04, 0xe3, 0x31, 0xdc, 0x22, 0x91, 0x69, 0x51, 0x9e, 0xc0, 0x2c, 0x74,
	0x56, 0x89, 0x52, 0xd4, 0x85, 0x4e, 0xa3, 0x54, 0x70, 0xd8, 0xb3, 0xa8, 0xf6, 0x4a, 0x51, 0x2f,
	0xf5, 0x88, 0xd5, 0xbb, 0x80, 0xf5, 0x35, 0xbe, 0x76, 0x0d, 0x6a, 0x6c, 0x3b, 0x8a, 0xa8, 0xf1,
	0xf9, 0x05, 0x29, 0x4e, 0x1c, 0x39, 0x87, 0x23, 0x22, 0x77, 0xef, 0x9e, 0x70, 0x50, 0x8b, 0x52,
	0xd4, 0x73, 0xfd, 0xc9, 0x72, 0x0d, 0xfb, 0xc6, 0xfb, 0x8d, 0x55, 0xcb, 0x2c, 0x30, 0x24, 0x87,
	0xcd, 0xb7, 0x37, 0x56, 0xad, 0xd8, 0x31, 0x72, 0xd2, 0xfc, 0xce, 0xc4, 0x47, 0x17, 0x7a, 0x75,
	0xcc, 0xda, 0xc8, 0x55, 0x0b, 0x67, 0x3f, 0x32, 0x91, 0x77, 0x03, 0x4d, 0x35, 0x93, 0x50, 0x34,
	0xce, 0x72, 0xad, 0xb9, 0xce, 0x73, 0xda, 0x59, 0xa4, 0x46, 0xcd, 0x78, 0x97, 0xe6, 0x14, 0x30,
	0x7e, 0x49, 0xce, 0x50, 0xbd, 0x09, 0x90, 0xfc, 0xa5, 0x9b, 0xf4, 0x5b, 0x7f, 0xef, 0x3e, 0x69,
	0xff, 0xe7, 0xd6, 0x77, 0x70, 0xfa, 0x2d, 0xcb, 0x5f, 0x3b, 0x6f, 0x0f, 0xf2, 0x2b, 0xb9, 0xfc,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x24, 0xed, 0xef, 0x23, 0x34, 0x02, 0x00, 0x00,
}
