// Code generated by protoc-gen-go.
// source: session.proto
// DO NOT EDIT!

/*
Package session is a generated protocol buffer package.

It is generated from these files:
	session.proto

It has these top-level messages:
	SessionInfo
	CreateSessionRequest
	CreateSessionReply
*/
package session

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SessionInfo struct {
	SessionId uint64 `protobuf:"varint,11,opt,name=sessionId" json:"sessionId,omitempty"`
}

func (m *SessionInfo) Reset()                    { *m = SessionInfo{} }
func (m *SessionInfo) String() string            { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()               {}
func (*SessionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SessionInfo) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type CreateSessionRequest struct {
	Rid          uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	AppId        string `protobuf:"bytes,11,opt,name=appId" json:"appId,omitempty"`
	CreateUserId string `protobuf:"bytes,12,opt,name=createUserId" json:"createUserId,omitempty"`
	Count        int32  `protobuf:"varint,13,opt,name=count" json:"count,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateSessionRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateSessionRequest) GetCreateUserId() string {
	if m != nil {
		return m.CreateUserId
	}
	return ""
}

func (m *CreateSessionRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateSessionReply struct {
	Rid        uint64         `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code       string         `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc       string         `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	SessionIds []*SessionInfo `protobuf:"bytes,11,rep,name=sessionIds" json:"sessionIds,omitempty"`
}

func (m *CreateSessionReply) Reset()                    { *m = CreateSessionReply{} }
func (m *CreateSessionReply) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionReply) ProtoMessage()               {}
func (*CreateSessionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateSessionReply) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionReply) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateSessionReply) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateSessionReply) GetSessionIds() []*SessionInfo {
	if m != nil {
		return m.SessionIds
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionInfo)(nil), "session.SessionInfo")
	proto.RegisterType((*CreateSessionRequest)(nil), "session.CreateSessionRequest")
	proto.RegisterType((*CreateSessionReply)(nil), "session.CreateSessionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Session service

type SessionClient interface {
	// Sends a greeting
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error) {
	out := new(CreateSessionReply)
	err := grpc.Invoke(ctx, "/session.Session/CreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Session service

type SessionServer interface {
	// Sends a greeting
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error)
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/session.Session/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "session.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Session_CreateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}

func init() { proto.RegisterFile("session.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x75, 0x4d, 0x6b, 0xe9, 0x24, 0x01, 0x19, 0x72, 0x58, 0xb4, 0x42, 0xd8, 0x53, 0x40, 0xe8,
	0xa1, 0xfa, 0x0b, 0xea, 0x29, 0x87, 0x42, 0x59, 0x11, 0xbc, 0xd6, 0xec, 0x08, 0x85, 0x92, 0x5d,
	0xb3, 0x29, 0xd8, 0xbb, 0x3f, 0x5c, 0xf6, 0xa3, 0xb5, 0x95, 0xf6, 0xf6, 0xe6, 0xbd, 0x79, 0x33,
	0xbb, 0x6f, 0x20, 0xb7, 0x64, 0xed, 0x5a, 0xb7, 0x53, 0xd3, 0xe9, 0x5e, 0xe3, 0x28, 0x96, 0xe2,
	0x11, 0xd2, 0xd7, 0x00, 0xeb, 0xf6, 0x53, 0xe3, 0x04, 0xc6, 0x51, 0xa9, 0x15, 0x4f, 0x4b, 0x56,
	0x0d, 0xe4, 0x1f, 0x21, 0xbe, 0xa1, 0x78, 0xe9, 0x68, 0xd5, 0x53, 0xb4, 0x48, 0xfa, 0xda, 0x92,
	0xed, 0xf1, 0x16, 0x92, 0x6e, 0xad, 0x38, 0xf3, 0xfd, 0x0e, 0x62, 0x01, 0xc3, 0x95, 0x31, 0x71,
	0xc6, 0x58, 0x86, 0x02, 0x05, 0x64, 0x8d, 0xf7, 0xbf, 0x59, 0xea, 0x6a, 0xc5, 0x33, 0x2f, 0x9e,
	0x70, 0xce, 0xd9, 0xe8, 0x6d, 0xdb, 0xf3, 0xbc, 0x64, 0xd5, 0x50, 0x86, 0x42, 0xfc, 0x30, 0xc0,
	0x7f, 0xab, 0xcd, 0x66, 0x77, 0x66, 0x31, 0xc2, 0xa0, 0xd1, 0x8a, 0xf8, 0xb5, 0x1f, 0xed, 0xb1,
	0xe3, 0x14, 0xd9, 0x86, 0x27, 0x81, 0x73, 0x18, 0x9f, 0x01, 0x0e, 0xff, 0xb2, 0x3c, 0x2d, 0x93,
	0x2a, 0x9d, 0x15, 0xd3, 0x7d, 0x48, 0x47, 0x91, 0xc8, 0xa3, 0xbe, 0xd9, 0x3b, 0x8c, 0xa2, 0x84,
	0x0b, 0xc8, 0x4f, 0x1e, 0x84, 0x0f, 0x07, 0xf7, 0xb9, 0x8c, 0xee, 0xee, 0x2f, 0xc9, 0x66, 0xb3,
	0x13, 0x57, 0xf3, 0x09, 0x40, 0xbd, 0xd8, 0xef, 0x9d, 0x67, 0x11, 0x2c, 0xdd, 0xb1, 0x96, 0xec,
	0xe3, 0xc6, 0x5f, 0xed, 0xe9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x73, 0xf8, 0xc6, 0x82, 0xc6, 0x01,
	0x00, 0x00,
}
