// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	CreateMessageRequest
	CreateMessageReply
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateMessageRequest struct {
	Rid       uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	SessionId int64  `protobuf:"varint,11,opt,name=sessionId" json:"sessionId,omitempty"`
	Type      int32  `protobuf:"varint,12,opt,name=type" json:"type,omitempty"`
	Content   string `protobuf:"bytes,13,opt,name=Content,json=content" json:"Content,omitempty"`
}

func (m *CreateMessageRequest) Reset()                    { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()               {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateMessageRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateMessageRequest) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CreateMessageRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateMessageReply struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *CreateMessageReply) Reset()                    { *m = CreateMessageReply{} }
func (m *CreateMessageReply) String() string            { return proto.CompactTextString(m) }
func (*CreateMessageReply) ProtoMessage()               {}
func (*CreateMessageReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateMessageReply) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateMessageReply) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateMessageReply) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMessageRequest)(nil), "message.CreateMessageRequest")
	proto.RegisterType((*CreateMessageReply)(nil), "message.CreateMessageReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Message service

type MessageClient interface {
	// Sends a greeting
	CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageReply, error)
}

type messageClient struct {
	cc *grpc.ClientConn
}

func NewMessageClient(cc *grpc.ClientConn) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) CreateMessage(ctx context.Context, in *CreateMessageRequest, opts ...grpc.CallOption) (*CreateMessageReply, error) {
	out := new(CreateMessageReply)
	err := grpc.Invoke(ctx, "/message.Message/CreateMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Message service

type MessageServer interface {
	// Sends a greeting
	CreateMessage(context.Context, *CreateMessageRequest) (*CreateMessageReply, error)
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/message.Message/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).CreateMessage(ctx, req.(*CreateMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessage",
			Handler:    _Message_CreateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x8d, 0xad, 0x86, 0x1d, 0xb7, 0x20, 0x83, 0x87, 0xa0, 0x2b, 0x84, 0x9e, 0x72, 0xea,
	0x41, 0xdf, 0x60, 0xf7, 0xb4, 0x87, 0xca, 0x92, 0x93, 0xd7, 0xb5, 0x19, 0x64, 0xa1, 0x36, 0xb1,
	0x89, 0x87, 0xbe, 0xbd, 0x24, 0x8d, 0x88, 0xd2, 0xbd, 0x7d, 0xf3, 0x85, 0xcc, 0xf0, 0xff, 0x50,
	0x7d, 0x90, 0xf7, 0xc7, 0x77, 0x6a, 0xdc, 0x68, 0x83, 0x45, 0x9e, 0xc7, 0x3a, 0xc0, 0xdd, 0x6e,
	0xa4, 0x63, 0xa0, 0x76, 0x16, 0x9a, 0x3e, 0xbf, 0xc8, 0x07, 0xbc, 0x85, 0x62, 0x3c, 0x19, 0xc1,
	0x24, 0x53, 0xa5, 0x8e, 0x88, 0x1b, 0x58, 0x79, 0xf2, 0xfe, 0x64, 0x87, 0xbd, 0x11, 0x37, 0x92,
	0xa9, 0x42, 0xff, 0x0a, 0x44, 0x28, 0xc3, 0xe4, 0x48, 0xac, 0x25, 0x53, 0x57, 0x3a, 0x31, 0x0a,
	0xe0, 0x3b, 0x3b, 0x04, 0x1a, 0x82, 0xa8, 0x24, 0x53, 0x2b, 0xcd, 0xbb, 0x79, 0xac, 0x5f, 0x00,
	0xff, 0x5d, 0x75, 0xfd, 0xb4, 0x70, 0x13, 0xa1, 0xec, 0xac, 0x21, 0x71, 0x99, 0xbe, 0x27, 0x8e,
	0xce, 0x90, 0xef, 0x44, 0x31, 0xbb, 0xc8, 0x4f, 0xaf, 0xc0, 0xf3, 0x26, 0x6c, 0xa1, 0xfa, 0xb3,
	0x1a, 0x1f, 0x9b, 0x9f, 0xe8, 0x4b, 0x41, 0xef, 0x1f, 0xce, 0x3d, 0xbb, 0x7e, 0xaa, 0x2f, 0xb6,
	0x1b, 0x80, 0x7d, 0xdb, 0x64, 0xb9, 0x5d, 0x67, 0x38, 0xc4, 0x12, 0x0f, 0xec, 0xed, 0x3a, 0xb5,
	0xf9, 0xfc, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x9c, 0xd0, 0xb1, 0x5e, 0x01, 0x00, 0x00,
}
