// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DeviceLoginRequest struct {
	Rid      uint64 `protobuf:"varint,1,opt,name=Rid,json=rid" json:"Rid,omitempty"`
	Token    string `protobuf:"bytes,11,opt,name=Token,json=token" json:"Token,omitempty"`
	AppId    string `protobuf:"bytes,12,opt,name=AppId,json=appId" json:"AppId,omitempty"`
	DeviceId string `protobuf:"bytes,13,opt,name=DeviceId,json=deviceId" json:"DeviceId,omitempty"`
	Platform string `protobuf:"bytes,14,opt,name=Platform,json=platform" json:"Platform,omitempty"`
	UserId   string `protobuf:"bytes,15,opt,name=UserId,json=userId" json:"UserId,omitempty"`
}

func (m *DeviceLoginRequest) Reset()                    { *m = DeviceLoginRequest{} }
func (m *DeviceLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceLoginRequest) ProtoMessage()               {}
func (*DeviceLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *DeviceLoginRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeviceLoginRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeviceLoginRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceLoginRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *DeviceLoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// messageType = 14
type DeviceLoginResponse struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *DeviceLoginResponse) Reset()                    { *m = DeviceLoginResponse{} }
func (m *DeviceLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceLoginResponse) ProtoMessage()               {}
func (*DeviceLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *DeviceLoginResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceLoginResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DeviceLoginResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceLoginRequest)(nil), "client.DeviceLoginRequest")
	proto.RegisterType((*DeviceLoginResponse)(nil), "client.DeviceLoginResponse")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x90, 0xcd, 0x4a, 0x43, 0x31,
	0x10, 0x85, 0x89, 0xb7, 0x0d, 0x75, 0xea, 0x1f, 0x51, 0x64, 0x70, 0x55, 0xba, 0xea, 0xca, 0x8d,
	0x4f, 0x20, 0xb8, 0xb9, 0x20, 0x28, 0x41, 0x1f, 0xa0, 0x66, 0x46, 0x09, 0x5e, 0x93, 0x98, 0xa4,
	0x3e, 0x90, 0x4f, 0x5a, 0x26, 0xe9, 0xa6, 0xbb, 0xf3, 0x9d, 0x8f, 0x84, 0xc3, 0xc0, 0x72, 0x8a,
	0x5f, 0x3e, 0xdc, 0xa7, 0x1c, 0x6b, 0x34, 0xda, 0x4d, 0x9e, 0x43, 0x5d, 0xff, 0x2b, 0x30, 0x4f,
	0xfc, 0xe7, 0x1d, 0x3f, 0x8b, 0xb5, 0xfc, 0xbb, 0xe3, 0x52, 0xcd, 0x15, 0x0c, 0xd6, 0x13, 0xaa,
	0x95, 0xda, 0xcc, 0xec, 0x90, 0x3d, 0x99, 0x1b, 0x98, 0xbf, 0xc5, 0x6f, 0x0e, 0xb8, 0x5c, 0xa9,
	0xcd, 0xa9, 0x9d, 0x57, 0x01, 0x69, 0x1f, 0x53, 0x1a, 0x09, 0xcf, 0x7a, 0xbb, 0x15, 0x30, 0x77,
	0xb0, 0xe8, 0x7f, 0x8e, 0x84, 0xe7, 0x4d, 0x2c, 0xe8, 0xc0, 0xe2, 0x5e, 0xa7, 0x6d, 0xfd, 0x8c,
	0xf9, 0x07, 0x2f, 0xba, 0x4b, 0x07, 0x36, 0xb7, 0xa0, 0xdf, 0x0b, 0xe7, 0x91, 0xf0, 0xb2, 0x19,
	0xbd, 0x6b, 0xb4, 0x7e, 0x81, 0xeb, 0xa3, 0x8d, 0x25, 0xc5, 0x50, 0x58, 0x46, 0xe6, 0xe3, 0x91,
	0x06, 0x66, 0x2e, 0x12, 0xe3, 0x49, 0x7b, 0xde, 0xb2, 0x74, 0xc4, 0xc5, 0xe1, 0xd0, 0x3b, 0xc9,
	0x1f, 0xba, 0x1d, 0xe1, 0x61, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xf5, 0x79, 0xe8, 0x13, 0x01,
	0x00, 0x00,
}
