// Code generated by protoc-gen-go.
// source: registe.proto
// DO NOT EDIT!

package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type DeviceRegisteRequest struct {
	Rid      uint64 `protobuf:"varint,1,opt,name=Rid,json=rid" json:"Rid,omitempty"`
	SsoToken string `protobuf:"bytes,11,opt,name=SsoToken,json=ssoToken" json:"SsoToken,omitempty"`
	AppId    string `protobuf:"bytes,12,opt,name=AppId,json=appId" json:"AppId,omitempty"`
	DeviceId string `protobuf:"bytes,13,opt,name=DeviceId,json=deviceId" json:"DeviceId,omitempty"`
	Platform string `protobuf:"bytes,14,opt,name=Platform,json=platform" json:"Platform,omitempty"`
}

func (m *DeviceRegisteRequest) Reset()                    { *m = DeviceRegisteRequest{} }
func (m *DeviceRegisteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceRegisteRequest) ProtoMessage()               {}
func (*DeviceRegisteRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *DeviceRegisteRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceRegisteRequest) GetSsoToken() string {
	if m != nil {
		return m.SsoToken
	}
	return ""
}

func (m *DeviceRegisteRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeviceRegisteRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceRegisteRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

type DeviceRegisteResponse struct {
	Rid   uint64 `protobuf:"varint,1,opt,name=Rid,json=rid" json:"Rid,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=Code,json=code" json:"Code,omitempty"`
	Desc  string `protobuf:"bytes,3,opt,name=Desc,json=desc" json:"Desc,omitempty"`
	Token string `protobuf:"bytes,11,opt,name=Token,json=token" json:"Token,omitempty"`
}

func (m *DeviceRegisteResponse) Reset()                    { *m = DeviceRegisteResponse{} }
func (m *DeviceRegisteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceRegisteResponse) ProtoMessage()               {}
func (*DeviceRegisteResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *DeviceRegisteResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceRegisteResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DeviceRegisteResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *DeviceRegisteResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceRegisteRequest)(nil), "client.DeviceRegisteRequest")
	proto.RegisterType((*DeviceRegisteResponse)(nil), "client.DeviceRegisteResponse")
}

func init() { proto.RegisterFile("registe.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4a, 0xc5, 0x30,
	0x10, 0x40, 0x89, 0x6d, 0x3f, 0xdf, 0x68, 0x45, 0x42, 0x85, 0xe0, 0xaa, 0x74, 0xd5, 0x95, 0x1b,
	0x4f, 0x20, 0x76, 0xd3, 0x9d, 0x44, 0x2f, 0x50, 0x33, 0x63, 0x09, 0xd6, 0x4e, 0xcc, 0x44, 0x0f,
	0xe2, 0x89, 0x25, 0x4d, 0x17, 0x22, 0x7f, 0xf9, 0xe6, 0x31, 0xc3, 0x63, 0x64, 0x1d, 0x70, 0x76,
	0x1c, 0xf1, 0xce, 0x07, 0x8a, 0xa4, 0x0e, 0x76, 0x71, 0xb8, 0xc6, 0xee, 0x47, 0xc8, 0x66, 0xc0,
	0x6f, 0x67, 0xd1, 0x64, 0x6f, 0xf0, 0xf3, 0x0b, 0x39, 0xaa, 0x6b, 0x59, 0x18, 0x07, 0x5a, 0xb4,
	0xa2, 0x2f, 0x4d, 0x11, 0x1c, 0xa8, 0x5b, 0x79, 0x7c, 0x66, 0x7a, 0xa1, 0x77, 0x5c, 0xf5, 0x45,
	0x2b, 0xfa, 0x73, 0x73, 0xe4, 0x9d, 0x55, 0x23, 0xab, 0x07, 0xef, 0x47, 0xd0, 0x97, 0x9b, 0xa8,
	0xa6, 0x04, 0x69, 0x23, 0xdf, 0x1e, 0x41, 0xd7, 0x79, 0x03, 0x76, 0x4e, 0xee, 0x69, 0x99, 0xe2,
	0x1b, 0x85, 0x0f, 0x7d, 0x95, 0x9d, 0xdf, 0xb9, 0x9b, 0xe5, 0xcd, 0xbf, 0x26, 0xf6, 0xb4, 0x32,
	0x9e, 0x88, 0x52, 0xb2, 0x7c, 0x24, 0x40, 0x7d, 0xb6, 0x9d, 0x28, 0x2d, 0x01, 0xa6, 0xd9, 0x80,
	0x6c, 0x75, 0x91, 0x67, 0x80, 0x6c, 0x53, 0xe0, 0xdf, 0xf2, 0x2a, 0x26, 0x78, 0x3d, 0x6c, 0xcf,
	0xb8, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x40, 0x1d, 0x8c, 0x44, 0x1d, 0x01, 0x00, 0x00,
}
