// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RpcRequest struct {
	Rid         uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	AppId       string `protobuf:"bytes,11,opt,name=appId" json:"appId,omitempty"`
	MessageType int32  `protobuf:"varint,12,opt,name=messageType" json:"messageType,omitempty"`
	ProtoBuf    []byte `protobuf:"bytes,13,opt,name=protoBuf,proto3" json:"protoBuf,omitempty"`
}

func (m *RpcRequest) Reset()                    { *m = RpcRequest{} }
func (m *RpcRequest) String() string            { return proto.CompactTextString(m) }
func (*RpcRequest) ProtoMessage()               {}
func (*RpcRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *RpcRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *RpcRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *RpcRequest) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *RpcRequest) GetProtoBuf() []byte {
	if m != nil {
		return m.ProtoBuf
	}
	return nil
}

type RpcResponse struct {
	Rid         uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc        string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	MessageType int32  `protobuf:"varint,11,opt,name=messageType" json:"messageType,omitempty"`
	ProtoBuf    []byte `protobuf:"bytes,12,opt,name=protoBuf,proto3" json:"protoBuf,omitempty"`
}

func (m *RpcResponse) Reset()                    { *m = RpcResponse{} }
func (m *RpcResponse) String() string            { return proto.CompactTextString(m) }
func (*RpcResponse) ProtoMessage()               {}
func (*RpcResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *RpcResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *RpcResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RpcResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *RpcResponse) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *RpcResponse) GetProtoBuf() []byte {
	if m != nil {
		return m.ProtoBuf
	}
	return nil
}

func init() {
	proto.RegisterType((*RpcRequest)(nil), "client.RpcRequest")
	proto.RegisterType((*RpcResponse)(nil), "client.RpcResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rpc service

type RpcClient interface {
	// Sends a greeting
	CreateMessage(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error)
}

type rpcClient struct {
	cc *grpc.ClientConn
}

func NewRpcClient(cc *grpc.ClientConn) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) CreateMessage(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error) {
	out := new(RpcResponse)
	err := grpc.Invoke(ctx, "/client.Rpc/CreateMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rpc service

type RpcServer interface {
	// Sends a greeting
	CreateMessage(context.Context, *RpcRequest) (*RpcResponse, error)
}

func RegisterRpcServer(s *grpc.Server, srv RpcServer) {
	s.RegisterService(&_Rpc_serviceDesc, srv)
}

func _Rpc_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/client.Rpc/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).CreateMessage(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "client.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMessage",
			Handler:    _Rpc_CreateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x31, 0x69, 0xa3, 0xf6, 0x92, 0x4a, 0xe8, 0xe8, 0x60, 0x75, 0xb2, 0x32, 0x65, 0xca,
	0x00, 0x1b, 0x1b, 0x61, 0xea, 0x50, 0xa9, 0x3a, 0xf1, 0x02, 0xc1, 0x39, 0x50, 0x25, 0x68, 0x0e,
	0x3b, 0x1d, 0x78, 0x00, 0xde, 0x1b, 0xd9, 0x96, 0x80, 0x20, 0xd4, 0xed, 0xbf, 0x4f, 0xb2, 0xbf,
	0x5f, 0x3f, 0x2c, 0x9d, 0xd8, 0x46, 0xdc, 0x30, 0x0e, 0x98, 0xdb, 0xd7, 0x03, 0x1f, 0xc7, 0xca,
	0x01, 0x90, 0x58, 0xe2, 0xf7, 0x13, 0xfb, 0x11, 0xaf, 0x20, 0x73, 0x87, 0x5e, 0x2b, 0xa3, 0xea,
	0x19, 0x85, 0x88, 0x6b, 0x98, 0x77, 0x22, 0xdb, 0x5e, 0x17, 0x46, 0xd5, 0x4b, 0x4a, 0x07, 0x1a,
	0x28, 0xde, 0xd8, 0xfb, 0xee, 0x85, 0x1f, 0x3f, 0x84, 0x75, 0x69, 0x54, 0x3d, 0xa7, 0xdf, 0x08,
	0x37, 0xb0, 0x88, 0xa2, 0xf6, 0xf4, 0xac, 0x57, 0x46, 0xd5, 0x25, 0x7d, 0xdf, 0xd5, 0xa7, 0x82,
	0x22, 0x4a, 0xbd, 0x0c, 0x47, 0xcf, 0xff, 0x58, 0x11, 0x66, 0x76, 0xe8, 0x59, 0x5f, 0x46, 0x69,
	0xcc, 0x81, 0xf5, 0xec, 0xad, 0xce, 0x12, 0x0b, 0xf9, 0x6f, 0x8f, 0xe2, 0x7c, 0x8f, 0x72, 0xda,
	0xe3, 0xe6, 0x1e, 0x32, 0x12, 0x8b, 0x77, 0xb0, 0x7a, 0x70, 0xdc, 0x8d, 0xbc, 0x4b, 0xef, 0x10,
	0x9b, 0x34, 0x4e, 0xf3, 0xb3, 0xcc, 0xe6, 0x7a, 0xc2, 0x52, 0xf1, 0xea, 0xa2, 0x5d, 0x43, 0xbe,
	0xdd, 0x05, 0xd6, 0x2e, 0x48, 0xec, 0x3e, 0xfc, 0xbc, 0x57, 0x4f, 0x79, 0x54, 0xdc, 0x7e, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xf7, 0xb8, 0xf5, 0xb2, 0x70, 0x01, 0x00, 0x00,
}
