// Code generated by protoc-gen-go.
// source: commonResponse.proto
// DO NOT EDIT!

/*
Package bean is a generated protocol buffer package.

It is generated from these files:
	commonResponse.proto
	login.proto
	message.proto
	registe.proto
	session.proto
	syncInform.proto
	Wraper.proto

It has these top-level messages:
	CommonResponse
	DeviceLoginRequest
	DeviceLoginResponse
	CreateMessageRequest
	CreateMessageResponse
	DeviceRegisteRequest
	DeviceRegisteResponse
	Session
	CreateSessionRequest
	CreateSessionResponse
	SyncInform
	WraperMessage
*/
package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 作为通用回应,messageType根据请求的情况而定
type CommonResponse struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *CommonResponse) Reset()                    { *m = CommonResponse{} }
func (m *CommonResponse) String() string            { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()               {}
func (*CommonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommonResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CommonResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CommonResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*CommonResponse)(nil), "bean.CommonResponse")
}

func init() { proto.RegisterFile("commonResponse.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0x0b, 0x4a, 0x2d, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x49, 0x4a, 0x4d, 0xcc, 0x53, 0xf2, 0xe2, 0xe2, 0x73, 0x46, 0x91, 0x15, 0x12, 0xe0,
	0x62, 0x2e, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x09, 0x02, 0x31, 0x85, 0x84, 0xb8,
	0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x90, 0x58,
	0x4a, 0x6a, 0x71, 0xb2, 0x04, 0x33, 0x44, 0x0c, 0xc4, 0x4e, 0x62, 0x03, 0x1b, 0x6c, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x29, 0xf6, 0xf6, 0x34, 0x70, 0x00, 0x00, 0x00,
}
