// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// messageType = 13
type DeviceLoginRequest struct {
	Rid      uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Token    string `protobuf:"bytes,11,opt,name=token" json:"token,omitempty"`
	AppId    string `protobuf:"bytes,12,opt,name=appId" json:"appId,omitempty"`
	DeviceId string `protobuf:"bytes,13,opt,name=deviceId" json:"deviceId,omitempty"`
	Platform string `protobuf:"bytes,14,opt,name=platform" json:"platform,omitempty"`
}

func (m *DeviceLoginRequest) Reset()                    { *m = DeviceLoginRequest{} }
func (m *DeviceLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceLoginRequest) ProtoMessage()               {}
func (*DeviceLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *DeviceLoginRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeviceLoginRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeviceLoginRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceLoginRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

// messageType = 14
type DeviceLoginResponse struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *DeviceLoginResponse) Reset()                    { *m = DeviceLoginResponse{} }
func (m *DeviceLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceLoginResponse) ProtoMessage()               {}
func (*DeviceLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *DeviceLoginResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceLoginResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DeviceLoginResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceLoginRequest)(nil), "bean.DeviceLoginRequest")
	proto.RegisterType((*DeviceLoginResponse)(nil), "bean.DeviceLoginResponse")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x4a, 0x4d, 0xcc, 0x53, 0xea, 0x62,
	0xe4, 0x12, 0x72, 0x49, 0x2d, 0xcb, 0x4c, 0x4e, 0xf5, 0x01, 0xc9, 0x05, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x08, 0x09, 0x70, 0x31, 0x17, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04,
	0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12, 0xdc, 0x0a, 0x8c, 0x1a,
	0x9c, 0x41, 0x10, 0x0e, 0x48, 0x34, 0xb1, 0xa0, 0xc0, 0x33, 0x45, 0x82, 0x07, 0x22, 0x0a, 0xe6,
	0x08, 0x49, 0x71, 0x71, 0xa4, 0x80, 0xcd, 0xf4, 0x4c, 0x91, 0xe0, 0x05, 0x4b, 0xc0, 0xf9, 0x20,
	0xb9, 0x82, 0x9c, 0xc4, 0x92, 0xb4, 0xfc, 0xa2, 0x5c, 0x09, 0x3e, 0x88, 0x1c, 0x8c, 0xaf, 0xe4,
	0xcf, 0x25, 0x8c, 0xe2, 0x96, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x2c, 0x8e, 0x11, 0xe2, 0x62,
	0x49, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x02, 0x1b, 0x00, 0x66, 0x83, 0xc4, 0x52, 0x52, 0x8b, 0x93,
	0x25, 0x98, 0x21, 0x62, 0x20, 0x76, 0x12, 0x1b, 0xd8, 0xab, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0xc8, 0xd0, 0x9f, 0xf9, 0x00, 0x00, 0x00,
}
