// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateMessageRequest struct {
	Rid       uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	SessionId int64  `protobuf:"varint,11,opt,name=sessionId" json:"sessionId,omitempty"`
	Type      int32  `protobuf:"varint,12,opt,name=type" json:"type,omitempty"`
	Content   string `protobuf:"bytes,13,opt,name=Content,json=content" json:"Content,omitempty"`
}

func (m *CreateMessageRequest) Reset()                    { *m = CreateMessageRequest{} }
func (m *CreateMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateMessageRequest) ProtoMessage()               {}
func (*CreateMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *CreateMessageRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateMessageRequest) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *CreateMessageRequest) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateMessageRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateMessageResponse struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *CreateMessageResponse) Reset()                    { *m = CreateMessageResponse{} }
func (m *CreateMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateMessageResponse) ProtoMessage()               {}
func (*CreateMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *CreateMessageResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateMessageResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateMessageResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateMessageRequest)(nil), "bean.CreateMessageRequest")
	proto.RegisterType((*CreateMessageResponse)(nil), "bean.CreateMessageResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0x8a, 0xc3, 0x30,
	0x0c, 0x40, 0xf1, 0xc5, 0x77, 0x21, 0xba, 0x0b, 0x1c, 0xa6, 0x05, 0x0d, 0x1d, 0x4c, 0x26, 0x4f,
	0x5d, 0xfa, 0x09, 0x99, 0x3a, 0x74, 0xa8, 0xff, 0x20, 0x89, 0x45, 0xc9, 0x50, 0x3b, 0x8d, 0xd4,
	0xa1, 0x7f, 0x5f, 0xe2, 0x0c, 0x85, 0xd2, 0xed, 0xe9, 0x09, 0xf4, 0x10, 0xd4, 0x57, 0x62, 0xee,
	0x2e, 0xb4, 0x9f, 0xe6, 0x24, 0xc9, 0xe8, 0x9e, 0xba, 0xd8, 0x08, 0x6c, 0xda, 0x99, 0x3a, 0xa1,
	0xd3, 0xba, 0xf4, 0x74, 0xbb, 0x13, 0x8b, 0xf9, 0x87, 0x62, 0x1e, 0x03, 0x2a, 0xab, 0x9c, 0xf6,
	0x0b, 0x9a, 0x1d, 0x54, 0x4c, 0xcc, 0x63, 0x8a, 0xc7, 0x80, 0xbf, 0x56, 0xb9, 0xc2, 0xbf, 0x84,
	0x31, 0xa0, 0xe5, 0x31, 0x11, 0xfe, 0x59, 0xe5, 0xbe, 0x7d, 0x66, 0x83, 0x50, 0xb6, 0x29, 0x0a,
	0x45, 0xc1, 0xda, 0x2a, 0x57, 0xf9, 0x72, 0x58, 0xc7, 0xe6, 0x0c, 0xdb, 0xb7, 0x2a, 0x4f, 0x29,
	0x32, 0x7d, 0xc8, 0x1a, 0xd0, 0x43, 0x0a, 0x84, 0x5f, 0xf9, 0x42, 0xe6, 0xc5, 0x05, 0xe2, 0x01,
	0x8b, 0xd5, 0x2d, 0xdc, 0xff, 0xe4, 0xaf, 0x0e, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0xc2,
	0xa8, 0xbc, 0xe6, 0x00, 0x00, 0x00,
}
