// Code generated by protoc-gen-go.
// source: session.proto
// DO NOT EDIT!

package bean

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Session struct {
	SessionId uint64 `protobuf:"varint,11,opt,name=sessionId" json:"sessionId,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Session) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type CreateSessionRequest struct {
	Rid          uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	AppId        string `protobuf:"bytes,11,opt,name=appId" json:"appId,omitempty"`
	CreateUserId string `protobuf:"bytes,12,opt,name=createUserId" json:"createUserId,omitempty"`
	Count        int32  `protobuf:"varint,13,opt,name=count" json:"count,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *CreateSessionRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateSessionRequest) GetCreateUserId() string {
	if m != nil {
		return m.CreateUserId
	}
	return ""
}

func (m *CreateSessionRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CreateSessionResponse struct {
	Rid        uint64     `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code       string     `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc       string     `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	SessionIds []*Session `protobuf:"bytes,11,rep,name=sessionIds" json:"sessionIds,omitempty"`
}

func (m *CreateSessionResponse) Reset()                    { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()               {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *CreateSessionResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateSessionResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateSessionResponse) GetSessionIds() []*Session {
	if m != nil {
		return m.SessionIds
	}
	return nil
}

func init() {
	proto.RegisterType((*Session)(nil), "bean.Session")
	proto.RegisterType((*CreateSessionRequest)(nil), "bean.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "bean.CreateSessionResponse")
}

func init() { proto.RegisterFile("session.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4e, 0xc6, 0x20,
	0x14, 0xc5, 0x83, 0xed, 0xa7, 0xf9, 0x6e, 0xdb, 0xc4, 0x90, 0x9a, 0x30, 0x38, 0x34, 0x2c, 0x76,
	0xb1, 0x83, 0x3e, 0x82, 0x53, 0x57, 0x8c, 0x0f, 0xd0, 0xc2, 0x1d, 0xba, 0x00, 0x72, 0x69, 0xe2,
	0xe8, 0xa3, 0x1b, 0xa0, 0xfe, 0x8d, 0xdb, 0xb9, 0x3f, 0xce, 0xbd, 0x27, 0x1c, 0xe8, 0x08, 0x89,
	0x36, 0x67, 0x27, 0x1f, 0x5c, 0x74, 0xbc, 0x5e, 0x71, 0xb1, 0xf2, 0x0e, 0xae, 0x9e, 0x0b, 0xe6,
	0xb7, 0x70, 0x3e, 0x1c, 0xb3, 0x11, 0xcd, 0xc0, 0xc6, 0x5a, 0x7d, 0x03, 0xf9, 0x06, 0xfd, 0x53,
	0xc0, 0x25, 0xe2, 0x61, 0x57, 0xf8, 0xba, 0x23, 0x45, 0x7e, 0x0d, 0x55, 0xd8, 0x8c, 0x60, 0xd9,
	0x9f, 0x24, 0xef, 0xe1, 0xb4, 0x78, 0x7f, 0xdc, 0x38, 0xab, 0x32, 0x70, 0x09, 0xad, 0xce, 0xfb,
	0x2f, 0x84, 0x61, 0x36, 0xa2, 0xcd, 0x8f, 0xbf, 0x58, 0xda, 0xd4, 0x6e, 0xb7, 0x51, 0x74, 0x03,
	0x1b, 0x4f, 0xaa, 0x0c, 0xf2, 0x9d, 0xc1, 0xcd, 0x9f, 0x68, 0xf2, 0xce, 0x12, 0xfe, 0x93, 0xcd,
	0xa1, 0xd6, 0xce, 0xa0, 0xb8, 0xc8, 0xd7, 0xb3, 0x4e, 0xcc, 0x20, 0x69, 0x51, 0x15, 0x96, 0x34,
	0xbf, 0x07, 0xf8, 0xfa, 0x1a, 0x89, 0x66, 0xa8, 0xc6, 0xe6, 0xa1, 0x9b, 0x52, 0x23, 0xd3, 0x67,
	0xc8, 0x0f, 0xc3, 0x7a, 0x99, 0x2b, 0x7b, 0xfc, 0x08, 0x00, 0x00, 0xff, 0xff, 0xe8, 0x9a, 0x9b,
	0x9a, 0x43, 0x01, 0x00, 0x00,
}
