// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	login.proto
	message.proto
	registe.proto
	response.proto
	rpc.proto
	session.proto

It has these top-level messages:
	DeviceLoginRequest
	DeviceLoginResponse
	CreateMessageRequest
	CreateMessageResponse
	DeviceRegisteRequest
	DeviceRegisteResponse
	Response
	RpcRequest
	RpcResponse
	SessionInfo
	CreateSessionRequest
	CreateSessionResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceLoginRequest struct {
	Rid      uint64 `protobuf:"varint,1,opt,name=Rid" json:"Rid,omitempty"`
	Token    string `protobuf:"bytes,11,opt,name=Token" json:"Token,omitempty"`
	AppId    string `protobuf:"bytes,12,opt,name=AppId" json:"AppId,omitempty"`
	DeviceId string `protobuf:"bytes,13,opt,name=DeviceId" json:"DeviceId,omitempty"`
	Platform string `protobuf:"bytes,14,opt,name=Platform" json:"Platform,omitempty"`
	UserId   string `protobuf:"bytes,15,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *DeviceLoginRequest) Reset()                    { *m = DeviceLoginRequest{} }
func (m *DeviceLoginRequest) String() string            { return proto.CompactTextString(m) }
func (*DeviceLoginRequest) ProtoMessage()               {}
func (*DeviceLoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceLoginRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceLoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeviceLoginRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *DeviceLoginRequest) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *DeviceLoginRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *DeviceLoginRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// messageType = 14
type DeviceLoginResponse struct {
	Rid  uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
}

func (m *DeviceLoginResponse) Reset()                    { *m = DeviceLoginResponse{} }
func (m *DeviceLoginResponse) String() string            { return proto.CompactTextString(m) }
func (*DeviceLoginResponse) ProtoMessage()               {}
func (*DeviceLoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeviceLoginResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *DeviceLoginResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DeviceLoginResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func init() {
	proto.RegisterType((*DeviceLoginRequest)(nil), "pb.DeviceLoginRequest")
	proto.RegisterType((*DeviceLoginResponse)(nil), "pb.DeviceLoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Login service

type LoginClient interface {
	// Sends a greeting
	Login(ctx context.Context, in *DeviceLoginRequest, opts ...grpc.CallOption) (*DeviceLoginResponse, error)
}

type loginClient struct {
	cc *grpc.ClientConn
}

func NewLoginClient(cc *grpc.ClientConn) LoginClient {
	return &loginClient{cc}
}

func (c *loginClient) Login(ctx context.Context, in *DeviceLoginRequest, opts ...grpc.CallOption) (*DeviceLoginResponse, error) {
	out := new(DeviceLoginResponse)
	err := grpc.Invoke(ctx, "/pb.Login/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Login service

type LoginServer interface {
	// Sends a greeting
	Login(context.Context, *DeviceLoginRequest) (*DeviceLoginResponse, error)
}

func RegisterLoginServer(s *grpc.Server, srv LoginServer) {
	s.RegisterService(&_Login_serviceDesc, srv)
}

func _Login_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Login/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginServer).Login(ctx, req.(*DeviceLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Login_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Login",
	HandlerType: (*LoginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Login_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "login.proto",
}

func init() { proto.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0xcb, 0x4a, 0xc5, 0x30,
	0x10, 0x86, 0xcd, 0xb9, 0xa1, 0x73, 0xbc, 0x31, 0x4a, 0x1d, 0xba, 0x2a, 0x5d, 0x75, 0xd5, 0x85,
	0xee, 0xdc, 0x89, 0x6e, 0x0a, 0x82, 0x12, 0xf4, 0x01, 0x6c, 0x33, 0x4a, 0xb0, 0x36, 0x31, 0xa9,
	0x3e, 0x90, 0x4f, 0x2a, 0x49, 0xac, 0x22, 0xdd, 0xfd, 0xff, 0xf7, 0x91, 0xc9, 0x30, 0xb0, 0xed,
	0xcd, 0x8b, 0x1e, 0x6a, 0xeb, 0xcc, 0x68, 0x70, 0x61, 0xdb, 0xf2, 0x4b, 0x00, 0xde, 0xf0, 0xa7,
	0xee, 0xf8, 0x36, 0x18, 0xc9, 0xef, 0x1f, 0xec, 0x47, 0x3c, 0x86, 0xa5, 0xd4, 0x8a, 0x44, 0x21,
	0xaa, 0x95, 0x0c, 0x11, 0x4f, 0x61, 0xfd, 0x60, 0x5e, 0x79, 0xa0, 0x6d, 0x21, 0xaa, 0x3d, 0x99,
	0x4a, 0xa0, 0x57, 0xd6, 0x36, 0x8a, 0xf6, 0x13, 0x8d, 0x05, 0x73, 0xd8, 0x4d, 0x33, 0x1b, 0x45,
	0x07, 0x51, 0xfc, 0xf6, 0xe0, 0xee, 0xfb, 0xa7, 0xf1, 0xd9, 0xb8, 0x37, 0x3a, 0x4c, 0x6e, 0xea,
	0x98, 0xc1, 0xe6, 0xd1, 0xb3, 0x6b, 0x14, 0x1d, 0x45, 0xf3, 0xd3, 0xca, 0x3b, 0x38, 0xf9, 0xb7,
	0xa3, 0xb7, 0x66, 0xf0, 0x1c, 0x96, 0x74, 0x7f, 0x4b, 0x3a, 0xad, 0x10, 0x61, 0xd5, 0x19, 0xc5,
	0xb4, 0x88, 0xcf, 0x63, 0x0e, 0x4c, 0xb1, 0xef, 0x68, 0x99, 0x58, 0xc8, 0xe7, 0xd7, 0xb0, 0x8e,
	0xa3, 0xf0, 0x72, 0x0a, 0x59, 0x6d, 0xdb, 0x7a, 0x7e, 0x88, 0xfc, 0x6c, 0xc6, 0xd3, 0xe7, 0xe5,
	0x4e, 0xbb, 0x89, 0x57, 0xbc, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x39, 0xe6, 0xfe, 0xf6, 0x54,
	0x01, 0x00, 0x00,
}
