// Code generated by protoc-gen-go.
// source: rpc.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RpcRequest struct {
	Rid         uint64 `protobuf:"varint,1,opt,name=Rid,json=rid" json:"Rid,omitempty"`
	AppId       string `protobuf:"bytes,2,opt,name=AppId,json=appId" json:"AppId,omitempty"`
	ConnId      uint64 `protobuf:"varint,3,opt,name=ConnId,json=connId" json:"ConnId,omitempty"`
	UserId      string `protobuf:"bytes,4,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	Token       string `protobuf:"bytes,5,opt,name=Token,json=token" json:"Token,omitempty"`
	MessageType int32  `protobuf:"varint,11,opt,name=messageType" json:"messageType,omitempty"`
	ProtoBuf    []byte `protobuf:"bytes,12,opt,name=protoBuf,proto3" json:"protoBuf,omitempty"`
}

func (m *RpcRequest) Reset()                    { *m = RpcRequest{} }
func (m *RpcRequest) String() string            { return proto.CompactTextString(m) }
func (*RpcRequest) ProtoMessage()               {}
func (*RpcRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *RpcRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *RpcRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *RpcRequest) GetConnId() uint64 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

func (m *RpcRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RpcRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RpcRequest) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *RpcRequest) GetProtoBuf() []byte {
	if m != nil {
		return m.ProtoBuf
	}
	return nil
}

type RpcResponse struct {
	Rid         uint64 `protobuf:"varint,1,opt,name=rid" json:"rid,omitempty"`
	Code        string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Desc        string `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	ConnId      uint64 `protobuf:"varint,4,opt,name=connId" json:"connId,omitempty"`
	MessageType int32  `protobuf:"varint,11,opt,name=messageType" json:"messageType,omitempty"`
	ProtoBuf    []byte `protobuf:"bytes,12,opt,name=protoBuf,proto3" json:"protoBuf,omitempty"`
}

func (m *RpcResponse) Reset()                    { *m = RpcResponse{} }
func (m *RpcResponse) String() string            { return proto.CompactTextString(m) }
func (*RpcResponse) ProtoMessage()               {}
func (*RpcResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *RpcResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *RpcResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *RpcResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *RpcResponse) GetConnId() uint64 {
	if m != nil {
		return m.ConnId
	}
	return 0
}

func (m *RpcResponse) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *RpcResponse) GetProtoBuf() []byte {
	if m != nil {
		return m.ProtoBuf
	}
	return nil
}

func init() {
	proto.RegisterType((*RpcRequest)(nil), "pb.RpcRequest")
	proto.RegisterType((*RpcResponse)(nil), "pb.RpcResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Rpc service

type RpcClient interface {
	// Sends a greeting
	Rpc(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error)
}

type rpcClient struct {
	cc *grpc.ClientConn
}

func NewRpcClient(cc *grpc.ClientConn) RpcClient {
	return &rpcClient{cc}
}

func (c *rpcClient) Rpc(ctx context.Context, in *RpcRequest, opts ...grpc.CallOption) (*RpcResponse, error) {
	out := new(RpcResponse)
	err := grpc.Invoke(ctx, "/pb.Rpc/Rpc", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Rpc service

type RpcServer interface {
	// Sends a greeting
	Rpc(context.Context, *RpcRequest) (*RpcResponse, error)
}

func RegisterRpcServer(s *grpc.Server, srv RpcServer) {
	s.RegisterService(&_Rpc_serviceDesc, srv)
}

func _Rpc_Rpc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServer).Rpc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Rpc/Rpc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServer).Rpc(ctx, req.(*RpcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Rpc",
	HandlerType: (*RpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Rpc",
			Handler:    _Rpc_Rpc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0xd0, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0x07, 0x70, 0xb3, 0xfd, 0xc0, 0x4e, 0x17, 0x95, 0x20, 0x12, 0xf6, 0x54, 0x7a, 0xca, 0xa9,
	0x82, 0x3e, 0x81, 0x7a, 0xea, 0x35, 0xac, 0x0f, 0xb0, 0x4d, 0x46, 0x59, 0xc4, 0x66, 0x4c, 0xda,
	0x83, 0x0f, 0xe3, 0x7b, 0xf8, 0x78, 0x92, 0xa9, 0xec, 0xea, 0x79, 0x4f, 0x99, 0xff, 0x30, 0x19,
	0x7e, 0x09, 0x54, 0x81, 0x6c, 0x47, 0xc1, 0x4f, 0x5e, 0xae, 0x68, 0x68, 0xbf, 0x05, 0x80, 0x21,
	0x6b, 0xf0, 0x63, 0xc6, 0x38, 0xc9, 0x2b, 0xc8, 0xcc, 0xde, 0x29, 0xd1, 0x08, 0x9d, 0x9b, 0x2c,
	0xec, 0x9d, 0xbc, 0x86, 0xe2, 0x81, 0xa8, 0x77, 0x6a, 0xd5, 0x08, 0x5d, 0x99, 0x62, 0x97, 0x82,
	0xbc, 0x81, 0xf2, 0xc9, 0x8f, 0x63, 0xef, 0x54, 0xc6, 0xa3, 0xa5, 0xe5, 0x94, 0xfa, 0xcf, 0x11,
	0x43, 0xef, 0x54, 0xce, 0xe3, 0xe5, 0xcc, 0x29, 0x6d, 0xd9, 0xfa, 0x37, 0x1c, 0x55, 0xb1, 0x6c,
	0x99, 0x52, 0x90, 0x0d, 0xd4, 0xef, 0x18, 0xe3, 0xee, 0x15, 0xb7, 0x9f, 0x84, 0xaa, 0x6e, 0x84,
	0x2e, 0xcc, 0xdf, 0x96, 0xdc, 0xc0, 0x39, 0x5b, 0x1f, 0xe7, 0x17, 0xb5, 0x6e, 0x84, 0x5e, 0x9b,
	0x43, 0x6e, 0xbf, 0x04, 0xd4, 0x4c, 0x8f, 0xe4, 0xc7, 0x88, 0xc9, 0x1e, 0xfe, 0xdb, 0x25, 0xe4,
	0xd6, 0x3b, 0xfc, 0xa5, 0x73, 0x9d, 0x7a, 0x0e, 0xa3, 0x65, 0x77, 0x65, 0xb8, 0x4e, 0xea, 0xc5,
	0xcf, 0xea, 0xe3, 0x6b, 0x4e, 0xf2, 0xdd, 0xdd, 0x42, 0x66, 0xc8, 0x4a, 0xbd, 0x1c, 0x17, 0x1d,
	0x0d, 0xdd, 0xf1, 0xa7, 0x37, 0x97, 0x87, 0xbc, 0xf0, 0xdb, 0xb3, 0xa1, 0xe4, 0xab, 0xf7, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xa6, 0xf9, 0xa8, 0x31, 0xa3, 0x01, 0x00, 0x00,
}
