// Code generated by protoc-gen-go.
// source: session.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SessionInfo struct {
	SessionId uint64 `protobuf:"varint,1,opt,name=SessionId" json:"SessionId,omitempty"`
}

func (m *SessionInfo) Reset()                    { *m = SessionInfo{} }
func (m *SessionInfo) String() string            { return proto.CompactTextString(m) }
func (*SessionInfo) ProtoMessage()               {}
func (*SessionInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *SessionInfo) GetSessionId() uint64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type SessionUserInfo struct {
	UserId string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
}

func (m *SessionUserInfo) Reset()                    { *m = SessionUserInfo{} }
func (m *SessionUserInfo) String() string            { return proto.CompactTextString(m) }
func (*SessionUserInfo) ProtoMessage()               {}
func (*SessionUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *SessionUserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type CreateSessionRequest struct {
	Rid          uint64             `protobuf:"varint,1,opt,name=Rid" json:"Rid,omitempty"`
	AppId        string             `protobuf:"bytes,11,opt,name=AppId" json:"AppId,omitempty"`
	SessionUsers []*SessionUserInfo `protobuf:"bytes,12,rep,name=SessionUsers" json:"SessionUsers,omitempty"`
}

func (m *CreateSessionRequest) Reset()                    { *m = CreateSessionRequest{} }
func (m *CreateSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionRequest) ProtoMessage()               {}
func (*CreateSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{2} }

func (m *CreateSessionRequest) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionRequest) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *CreateSessionRequest) GetSessionUsers() []*SessionUserInfo {
	if m != nil {
		return m.SessionUsers
	}
	return nil
}

type CreateSessionResponse struct {
	Rid     uint64       `protobuf:"varint,1,opt,name=Rid" json:"Rid,omitempty"`
	Code    string       `protobuf:"bytes,2,opt,name=Code" json:"Code,omitempty"`
	Desc    string       `protobuf:"bytes,3,opt,name=Desc" json:"Desc,omitempty"`
	Session *SessionInfo `protobuf:"bytes,11,opt,name=Session" json:"Session,omitempty"`
}

func (m *CreateSessionResponse) Reset()                    { *m = CreateSessionResponse{} }
func (m *CreateSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateSessionResponse) ProtoMessage()               {}
func (*CreateSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{3} }

func (m *CreateSessionResponse) GetRid() uint64 {
	if m != nil {
		return m.Rid
	}
	return 0
}

func (m *CreateSessionResponse) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateSessionResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CreateSessionResponse) GetSession() *SessionInfo {
	if m != nil {
		return m.Session
	}
	return nil
}

func init() {
	proto.RegisterType((*SessionInfo)(nil), "pb.SessionInfo")
	proto.RegisterType((*SessionUserInfo)(nil), "pb.SessionUserInfo")
	proto.RegisterType((*CreateSessionRequest)(nil), "pb.CreateSessionRequest")
	proto.RegisterType((*CreateSessionResponse)(nil), "pb.CreateSessionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Session service

type SessionClient interface {
	// Sends a greeting
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
}

type sessionClient struct {
	cc *grpc.ClientConn
}

func NewSessionClient(cc *grpc.ClientConn) SessionClient {
	return &sessionClient{cc}
}

func (c *sessionClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	out := new(CreateSessionResponse)
	err := grpc.Invoke(ctx, "/pb.Session/CreateSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Session service

type SessionServer interface {
	// Sends a greeting
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
}

func RegisterSessionServer(s *grpc.Server, srv SessionServer) {
	s.RegisterService(&_Session_serviceDesc, srv)
}

func _Session_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Session/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Session_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Session",
	HandlerType: (*SessionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _Session_CreateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "session.proto",
}

func init() { proto.RegisterFile("session.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0xb5, 0x4d, 0xad, 0x74, 0xd2, 0x52, 0x19, 0xab, 0xac, 0xe2, 0xa1, 0xec, 0xa9, 0x45, 0xc8,
	0x21, 0x1e, 0x3c, 0x4b, 0x45, 0xe8, 0xd1, 0x15, 0x3f, 0xc0, 0x98, 0x11, 0x7a, 0xc9, 0xae, 0x99,
	0x88, 0x17, 0x3f, 0x5e, 0x76, 0x76, 0x63, 0xdb, 0x90, 0xdb, 0x7b, 0x6f, 0x66, 0xde, 0x7b, 0xec,
	0xc2, 0x8c, 0x89, 0x79, 0x67, 0xab, 0xcc, 0xd5, 0xb6, 0xb1, 0x38, 0x74, 0x85, 0xbe, 0x83, 0xf4,
	0x35, 0x88, 0xdb, 0xea, 0xd3, 0xe2, 0x2d, 0x4c, 0x5a, 0x5a, 0xaa, 0xc1, 0x72, 0xb0, 0x1a, 0x99,
	0xbd, 0xa0, 0xd7, 0x30, 0x8f, 0xe4, 0x8d, 0xa9, 0x96, 0x83, 0x2b, 0x18, 0x0b, 0x0e, 0xdb, 0x13,
	0x13, 0x99, 0xfe, 0x81, 0xc5, 0xa6, 0xa6, 0xf7, 0x86, 0xe2, 0x81, 0xa1, 0xaf, 0x6f, 0xe2, 0x06,
	0xcf, 0x21, 0x31, 0xbb, 0xd6, 0xda, 0x43, 0x5c, 0xc0, 0xe9, 0xa3, 0x73, 0xdb, 0x52, 0xa5, 0x62,
	0x10, 0x08, 0x3e, 0xc0, 0xf4, 0x20, 0x8a, 0xd5, 0x74, 0x99, 0xac, 0xd2, 0xfc, 0x22, 0x73, 0x45,
	0xd6, 0xa9, 0x60, 0x8e, 0x16, 0xf5, 0x2f, 0x5c, 0x76, 0x82, 0xd9, 0xd9, 0x8a, 0xa9, 0x27, 0x19,
	0x61, 0xb4, 0xb1, 0x25, 0xa9, 0xa1, 0x04, 0x0b, 0xf6, 0xda, 0x13, 0xf1, 0x87, 0x4a, 0x82, 0xe6,
	0x31, 0xae, 0xe1, 0x2c, 0x9a, 0x49, 0xc7, 0x34, 0x9f, 0x1f, 0xd4, 0x90, 0x0a, 0xed, 0x3c, 0x7f,
	0xf9, 0x5f, 0xc5, 0x67, 0x98, 0x1d, 0x15, 0x41, 0xe5, 0xaf, 0xfa, 0x1e, 0xe5, 0xe6, 0xba, 0x67,
	0x12, 0x5a, 0xeb, 0x93, 0x62, 0x2c, 0x9f, 0x75, 0xff, 0x17, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x2e,
	0x62, 0x66, 0xbd, 0x01, 0x00, 0x00,
}
